// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFNxAFhaOnB0tIg-cE63OkPlZSaOx4PA0',
    appId: '1:133723485446:web:c53568210666dbbb3c9a87',
    messagingSenderId: '133723485446',
    projectId: 'skills-audit-system-cfa90',
    authDomain: 'skills-audit-system-cfa90.firebaseapp.com',
    storageBucket: 'skills-audit-system-cfa90.firebasestorage.app',
    measurementId: 'G-0ZZXRHHHP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3yOC-9K2SxU6OjH9vzVZxCB-LvGKXdUE',
    appId: '1:133723485446:android:e51ac1d62e8669763c9a87',
    messagingSenderId: '133723485446',
    projectId: 'skills-audit-system-cfa90',
    storageBucket: 'skills-audit-system-cfa90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpDIRU12XvvviW2Csbeq6Q7Vitqby5RR8',
    appId: '1:133723485446:ios:0886cf4f5a9077d83c9a87',
    messagingSenderId: '133723485446',
    projectId: 'skills-audit-system-cfa90',
    storageBucket: 'skills-audit-system-cfa90.firebasestorage.app',
    iosBundleId: 'com.example.skillsAuditSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpDIRU12XvvviW2Csbeq6Q7Vitqby5RR8',
    appId: '1:133723485446:ios:0886cf4f5a9077d83c9a87',
    messagingSenderId: '133723485446',
    projectId: 'skills-audit-system-cfa90',
    storageBucket: 'skills-audit-system-cfa90.firebasestorage.app',
    iosBundleId: 'com.example.skillsAuditSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFNxAFhaOnB0tIg-cE63OkPlZSaOx4PA0',
    appId: '1:133723485446:web:e154b003dcf2344f3c9a87',
    messagingSenderId: '133723485446',
    projectId: 'skills-audit-system-cfa90',
    authDomain: 'skills-audit-system-cfa90.firebaseapp.com',
    storageBucket: 'skills-audit-system-cfa90.firebasestorage.app',
    measurementId: 'G-1CD5QBQD8J',
  );
}
